#!/usr/bin/env node
/**
 * Vendor Inter so no page load contacts a third-party font host.
 * Google's stylesheet stays the source of truth for subsets and unicode-range;
 * this downloads every woff2 it references and rewrites the URLs to local paths.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const [, , outDir, publicPrefix] = process.argv;
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36';

const res = await fetch(
  'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap',
  { headers: { 'User-Agent': UA } }
);
if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
let css = await res.text();

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

const urls = [
  ...new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? []),
];
for (const url of urls) {
  const name = url.split('/').slice(-2).join('-');
  const f = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!f.ok) throw new Error(`${f.status} fetching ${url}`);
  await writeFile(resolve(outDir, name), Buffer.from(await f.arrayBuffer()));
  css = css.replaceAll(url, `${publicPrefix}/${name}`);
}

await writeFile(
  resolve(outDir, 'inter.css'),
  '/* Inter, self-hosted. Generated by scripts/vendor-inter.mjs — do not edit.\n' +
    '   Vendored so no page load contacts a third-party font host. */\n' +
    css
);
console.log(`${urls.length} woff2 + inter.css -> ${outDir}`);
