/*
 * Libre WebUI
 * Copyright (C) 2025 Kroonen AI, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The Libre WebUI Cordis host.
 *
 * This module owns the embedded Cordis runtime: it creates the root context,
 * installs the Loader, and mounts a composition document (`cordis.patch.yml`)
 * whose rows name the DSH engine plugins. Every service, event listener, and
 * route the composition installs is owned by the root fiber, so disposing the
 * root rolls all of it back — that single ownership edge is what makes the DSH
 * engine removable at runtime instead of merely disabled.
 *
 * The host deliberately does not import any `@deepseek-ai/dsh-*` module. It
 * names those packages only as strings inside the composition document, so the
 * DSH dependency stays configurable data rather than a compile-time import
 * graph, and an operator can mount a different engine by editing YAML.
 *
 * @module cordis/host/host
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Context } from '@deepseek-ai/cordis';
import Loader from '@deepseek-ai/cordis-plugin-loader';
import Include from '@deepseek-ai/cordis-plugin-include';
import Group from '@deepseek-ai/cordis-plugin-group';
import { createLogger } from '../../utils/logger.js';
import {
  applyHostDefaults,
  readCompositionFile,
  stringifyComposition,
} from './composition.js';
import type { CompositionEntry } from './composition.js';
import type { CordisHostConfig } from './config.js';
import { createLoaderEntry } from './loader-entry.js';
import {
  assertDshModuleAllowed,
  enforceDshPrivacy,
  isDshUploadPackage,
} from './privacy.js';
import {
  isServedByProviderLayer,
  LIBRE_WEBUI_ROUTE,
  requiredProviderPackage,
} from './model.js';

const logger = createLogger('cordis-host');

/**
 * Loader entry id of the composed engine tree. Stable because operators and
 * diagnostics address the tree by this id when they remove or inspect it.
 */
export const ENGINE_ENTRY_ID = 'libre-webui-engine';

/** Loader entry id of the row that mounts the Libre WebUI bridge. */
export const BRIDGE_ENTRY_ID = 'libre-webui-bridge';

/**
 * Row id of the composition's Libre WebUI provider adapter.
 *
 * Referenced only in the startup diagnostic, so an operator whose composition
 * predates the row is told exactly what to add.
 */
const MODEL_ADAPTER_ROW_ID = 'libre-webui-llm-adapter';

/**
 * Hand the provider capability to the composition's adapter module.
 *
 * The module is imported through the Loader's own base URL rather than by the
 * application, because a module imported by URL and one imported by path are
 * separate instances: registering the capability on the application's copy
 * would leave the row's copy without it, and the row would register no route.
 *
 * @param config - host configuration carrying the capability.
 */
async function installProviderCapability(
  config: CordisHostConfig,
  entries: readonly CompositionEntry[]
): Promise<void> {
  const handler = config.providerHandler;
  if (!handler) return;
  const row = entries.find(entry => entry.id === MODEL_ADAPTER_ROW_ID);
  if (!row || row.disabled === true) return;
  const specifier = row.name;
  assertDshModuleAllowed(specifier);
  const url = specifier.startsWith('.')
    ? pathToFileURL(specifier).href
    : specifier;
  const adapter = (await import(url)) as {
    setLibreWebUiProvider?: (next: unknown) => void;
  };
  adapter.setLibreWebUiProvider?.(handler);
}

/** File name of the host-composed copy of the operator's composition. */
export const COMPOSED_FILENAME = 'cordis.composed.yml';

/**
 * Header written above the host-composed document.
 *
 * The composed file lives in host-owned state and is regenerated on every
 * start, so a reader who finds it must be told not to edit it as if it were the
 * operator's composition.
 */
const COMPOSITION_HEADER = `# Generated by the Libre WebUI Cordis host. Do not edit.
# This is the host's copy of the operator's composition, with host-owned
# defaults merged into the engine bridge row. The authoritative document is
# cordis.patch.yml; edit that instead and restart the host.
`;

/** One service the host requires the composition to provide. */
export interface RequiredService {
  /** Cordis service name as registered on the context. */
  readonly name: string;
  /** Whether the composition must provide it for the host to report ready. */
  readonly required: boolean;
}

/**
 * Services the host expects from the DSH composition.
 *
 * `agents` and `tools` are required for a functioning engine. `sessionPersistence`
 * is required only when persistence is enabled, because an in-memory engine is a
 * legitimate configuration for tests and ephemeral deployments.
 */
export function requiredServices(config: CordisHostConfig): RequiredService[] {
  return [
    { name: 'llm', required: false },
    { name: 'systemPrompt', required: true },
    { name: 'sessions', required: true },
    { name: 'tools', required: true },
    { name: 'agents', required: true },
    { name: 'sessionProjections', required: true },
    {
      name: 'sessionPersistence',
      required: config.features.persistence,
    },
  ];
}

/** Observability snapshot of the running host. */
export interface CordisHostStatus {
  /** Whether the composition is mounted and the root fiber is active. */
  readonly started: boolean;
  /** Absolute path of the composition document in use. */
  readonly configPath: string;
  /** Services the composition provides, in requirement order. */
  readonly services: readonly {
    readonly name: string;
    readonly required: boolean;
    readonly available: boolean;
  }[];
  /** Names of required services that the composition did not provide. */
  readonly missing: readonly string[];
}

/** A mounted Cordis host. */
export interface CordisHost {
  /** Root context of the embedded runtime. */
  readonly context: Context;
  /** Configuration the host was resolved with. */
  readonly config: CordisHostConfig;
  /** Snapshot the current state of the host and its services. */
  status(): CordisHostStatus;
  /**
   * Dispose the whole Cordis tree, rolling back every service, listener, and
   * effect the composition installed.
   */
  stop(): Promise<void>;
}

/**
 * Base URL the composition resolves against.
 *
 * This is the backend package root, so a row may name a bundled plugin with a
 * relative specifier (`./dist/cordis/dsh/engine-plugin.js`) or a package with a
 * bare one (`@deepseek-ai/dsh-tools`). Pinning it here rather than deriving it
 * per row keeps one documented rule for both cases.
 */
const HOST_BASE_URL = new URL('../../../', import.meta.url).href;

/**
 * Fail startup when the configured model route has no adapter.
 *
 * A configured route with no adapter fails every turn with a message about a
 * missing adapter, which does not tell an operator that their composition
 * predates the row that provides it. Naming the gap at startup is the
 * difference between a fixable pointer and a mystery.
 *
 * Rows register as their dependencies become available, so the tree is given a
 * chance to quiesce first: a row merely slower than this check must not be
 * reported as absent.
 *
 * @param context - the mounted tree's root context.
 * @param config - the host configuration naming the route.
 * @throws when the route has no adapter, naming what to add.
 */
async function assertConfiguredRouteAvailable(
  context: Context,
  config: CordisHostConfig
): Promise<void> {
  const route =
    config.model.provider === 'libre-webui'
      ? LIBRE_WEBUI_ROUTE
      : config.model.route;
  if (route === '') return;
  let routes: string[] = [];
  for (let attempt = 0; attempt < 20; attempt += 1) {
    routes = (context.get('llm')?.listProviders?.() ?? []).map(
      (provider: { id: string }) => provider.id
    );
    if (routes.includes(route)) return;
    // Yield so a row still activating can finish before it is called missing.
    await new Promise(resolve => setTimeout(resolve, 25));
  }
  throw new Error(
    `cordis host: the composition provides no adapter for model route ` +
      `"${route}" (available: ${routes.join(', ') || 'none'}). ` +
      'Add the row that serves it — the shipped example mounts ' +
      `"${MODEL_ADAPTER_ROW_ID}" for the "libre-webui" route — or point ` +
      'model.route at a route the composition provides.'
  );
}

/**
 * Rewrite relative module specifiers to absolute file URLs.
 *
 * The host writes the composed document into its own runtime directory, and the
 * Cordis loader resolves a relative specifier against the document that named
 * it. A row writing `./dist/...` therefore resolved under the runtime directory
 * instead of the directory the operator wrote it in, and the row silently
 * failed to import — which surfaced only as every service it published being
 * reported missing. Resolving the names here keeps an operator's relative paths
 * meaning what they appear to mean, wherever the composed copy is written.
 *
 * @param entries - the composed entry list.
 * @param documentDirectory - directory of the operator's document.
 * @returns entries with relative names replaced by absolute file URLs.
 */
function absolutizeEntryNames(
  entries: readonly CompositionEntry[],
  documentDirectory: string
): CompositionEntry[] {
  return entries.map(entry => {
    const name = entry.name;
    if (!name.startsWith('./') && !name.startsWith('../')) return entry;
    return {
      ...entry,
      name: pathToFileURL(path.resolve(documentDirectory, name)).href,
    };
  });
}

/**
 * Resolver for the model the engine should use when its configuration names
 * none. Installed by the application, so the host does not import an
 * application module and the dependency keeps pointing one way.
 */
let engineDefaultModel: (() => Promise<string | undefined>) | undefined;

/**
 * Install the resolver for the engine's fallback model.
 * @param resolve - the resolver, or undefined to clear it.
 */
export function setEngineDefaultModelResolver(
  resolve: (() => Promise<string | undefined>) | undefined
): void {
  engineDefaultModel = resolve;
}

/**
 * Start the Cordis host and mount the configured DSH composition.
 *
 * The returned host is live: its services are reachable through
 * `host.context.get(name)`. Callers that need the engine contract should read
 * the `libreDshEngine` service instead of touching the context directly.
 *
 * @param config - fully resolved host configuration.
 * @returns the started host.
 * @throws when the composition document is missing, malformed, or fails to
 *   mount; a failed start disposes whatever was partially mounted first.
 */
export async function startCordisHost(
  config: CordisHostConfig
): Promise<CordisHost> {
  if (process.env.LIBRE_PLATFORM_MODE?.trim().toLowerCase() === 'team') {
    throw new Error(
      'The embedded Cordis engine requires the single-replica solo profile. Use the sandboxed Work integration in team deployments.'
    );
  }
  const context = new Context();
  enforceDshPrivacy(context);
  if (config.providerHandler)
    context.provide('libreCordisProvider', config.providerHandler);
  // Parse the document before creating any runtime state, so a malformed
  // composition fails without leaving a partially built context behind.
  const entries = readCompositionFile(config.configPath);
  if (
    entries.some(entry => entry.id === BRIDGE_ENTRY_ID) &&
    !entries.some(entry => entry.name === '@deepseek-ai/dsh-user-approval')
  ) {
    entries.push({
      id: 'libre-webui-approval',
      name: '@deepseek-ai/dsh-user-approval',
    });
  }
  const entryCount = entries.length;
  // The bridge needs the model route and model to pin on the agents it creates;
  // an agent with neither produces turns with no assistant response. Those two
  // values are host settings, so the host merges them into the row it names.
  // A model must be pinned on the bridge row: an agent with no provider/model
  // refuses every turn. When the settings document names none, the app's own
  // default is used so the engine behaves like the Chat surface.
  const defaultModel =
    config.model.model !== ''
      ? config.model.model
      : config.providerHandler
        ? undefined
        : await engineDefaultModel?.().catch(() => undefined);
  const composed = absolutizeEntryNames(
    applyHostDefaults(entries, BRIDGE_ENTRY_ID, {
      workspacePath: config.workspacePath,
      streaming: config.features.streaming,
      // The engine must always name a route, and in the provider-layer mode
      // that route is this deployment's own adapter — `route` describes a
      // provider package's route and is empty here.
      defaultProvider:
        config.model.provider === 'libre-webui'
          ? LIBRE_WEBUI_ROUTE
          : config.model.route,
      ...(defaultModel ? { defaultModel } : {}),
    }).map(entry => {
      const rowConfig =
        entry.config && typeof entry.config === 'object'
          ? (entry.config as Record<string, unknown>)
          : {};
      if (entry.id === BRIDGE_ENTRY_ID)
        return {
          ...entry,
          config: {
            ...rowConfig,
            workspacePath: config.workspacePath,
            streaming: config.features.streaming,
            tools: config.features.tools,
            sessionStorePath:
              config.features.persistence &&
              entries.some(
                row => row.name === '@deepseek-ai/dsh-session-persistence-jsonl'
              )
                ? config.sessionStorePath
                : undefined,
          },
        };
      if (entry.name === '@deepseek-ai/dsh-session-persistence-jsonl')
        return {
          ...entry,
          disabled: !config.features.persistence || entry.disabled === true,
          config: { ...rowConfig, root: config.sessionStorePath },
        };
      return entry;
    }),
    path.dirname(config.configPath)
  );
  const composedPath = path.join(config.runtimePath, COMPOSED_FILENAME);

  let contextDisposed = false;
  const host: CordisHost = {
    context,
    config,
    status: () => describeStatus(context, config, !contextDisposed),
    stop: async () => {
      if (contextDisposed) return;
      contextDisposed = true;
      await stopContext(context);
    },
  };

  try {
    // Materialize the composed document before the Loader reads it. The
    // directory is host-owned runtime state, recreated on every start so a
    // stale composition can never be picked up.
    mkdirSync(config.runtimePath, { recursive: true });
    writeFileSync(
      composedPath,
      `${COMPOSITION_HEADER}${stringifyComposition(composed)}`,
      'utf8'
    );

    // Hand the provider capability to the exact module the composition names.
    // A row is imported by URL while the application imports its own modules by
    // path, and those are separate module instances: a registration made on the
    // application's copy is invisible to the row's, so the row would register no
    // route and every turn would fail with "no adapter".
    await installProviderCapability(config, composed);

    await context.plugin(Loader, { baseUrl: HOST_BASE_URL });
    const loader = context.get('loader');
    if (!loader) {
      throw new Error('cordis host: the Loader service did not start');
    }
    // `cordis:group` is how one composition row gives a provider and its
    // consumers a shared isolate realm. The DSH bundle patches rely on it, so a
    // composition copied from DSH would fail to resolve it without this.
    loader.builtins.group = Group;
    // `cordis:include` is the tree carrier that turns a `plugins:` list into
    // loader entries. The host registers both carriers itself rather than
    // requiring every composition to list them.
    loader.builtins.include = Include;

    await createLoaderEntry(loader, {
      id: ENGINE_ENTRY_ID,
      name: 'cordis:include',
      config: {
        // Include reads this file itself and owns writing it back when an
        // entry changes. The host writes a composed copy into its own runtime
        // directory rather than the operator's file, so host-supplied defaults
        // never overwrite a document a human maintains, and Include's own
        // write-backs land somewhere disposable.
        path: pathToFileURL(composedPath).href,
      },
    });
    await loader.await();

    const requiredPackage = requiredProviderPackage(config.model);
    if (requiredPackage && !isServedByProviderLayer(config)) {
      throw new Error(
        `cordis host: model provider "${config.model.provider}" needs the ` +
          `"${requiredPackage}" package, which is not a dependency of this ` +
          'backend. Install it and mount its row in the composition, or set ' +
          'model.provider to "libre-webui" to use the providers this ' +
          'deployment already has.'
      );
    }
    await assertConfiguredRouteAvailable(context, config);

    const missing = host
      .status()
      .missing.filter(
        name => name !== 'sessionPersistence' || config.features.persistence
      );
    if (missing.length > 0) {
      // A service is missing because the row that provides it never activated,
      // and the most common cause is that the row failed to import — a wrong
      // path, or a package that is not installed. Naming that cause here is the
      // difference between "the engine is broken" and "fix this one row".
      const inactive = [...loader.entries()]
        .filter(
          entry =>
            entry.fiber === undefined &&
            // Disabled uploaders never provide a required engine service.
            !isDshUploadPackage(entry.options.name)
        )
        .map(entry => entry.options.id)
        .filter((id): id is string => typeof id === 'string');
      throw new Error(
        `cordis host: composition "${config.configPath}" did not provide required ` +
          `service(s): ${missing.join(', ')}` +
          (inactive.length > 0
            ? `. Row(s) that did not activate: ${inactive.join(', ')}. ` +
              'A row that failed to import never provides its service; run with ' +
              'LIBRE_CORDIS_TRACE=true for the activation log.'
            : '.')
      );
    }

    logger.info('Cordis host started', {
      configPath: config.configPath,
      entries: entryCount,
      provider: config.model.provider,
      route: config.model.route,
      workspace: config.workspacePath,
      persistence: config.features.persistence,
    });
    return host;
  } catch (error) {
    // A partially mounted tree still owns live services, timers, and file
    // handles. Roll it back before reporting, so a failed start never leaves a
    // half-composed engine attached to the process.
    contextDisposed = true;
    await stopContext(context);
    throw error;
  }
}

/**
 * Dispose a root context, containing failures so teardown always completes.
 *
 * Cordis already contains per-observer cleanup failures; this wrapper covers
 * the case where the root fiber itself rejects, which must not mask the
 * original startup error or leave the caller without a teardown result.
 * @param context - the root context to dispose.
 */
async function stopContext(context: Context): Promise<void> {
  try {
    await context.fiber.dispose();
    logger.info('Cordis host stopped; all engine effects rolled back');
  } catch (error) {
    // Teardown is best-effort by contract: a plugin that throws while unloading
    // must not prevent the remaining plugins from being disposed.
    logger.error('Cordis host teardown reported an error', {
      error: error instanceof Error ? error.message : String(error),
    });
  }
}

/** Build the status snapshot for a host. */
function describeStatus(
  context: Context,
  config: CordisHostConfig,
  started: boolean
): CordisHostStatus {
  const services = requiredServices(config).map(service => ({
    ...service,
    available: context.get(service.name) !== undefined,
  }));
  return {
    started,
    configPath: config.configPath,
    services,
    missing: services
      .filter(service => service.required && !service.available)
      .map(service => service.name),
  };
}
